"""Add OAuth fields

Revision ID: 80be64a7c450
Revises: 5686d5b60f5c
Create Date: 2025-12-10 16:41:40.066737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80be64a7c450'
down_revision = '5686d5b60f5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oauth_provider', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('oauth_id', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('oauth_id')
        batch_op.drop_column('oauth_provider')

    # ### end Alembic commands ###
