"""add adaptive search optimizer tables

Revision ID: affcbcaaec3c
Revises: 80be64a7c450
Create Date: 2026-05-30 12:03:41.252918

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affcbcaaec3c'
down_revision = '80be64a7c450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_variant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_key', sa.String(length=512), nullable=False),
    sa.Column('main_name', sa.String(length=512), nullable=False),
    sa.Column('variant', sa.String(length=256), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_key', 'variant', name='uq_product_variant')
    )
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_variant_product_key'), ['product_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_variant_variant'), ['variant'], unique=False)

    op.create_table('query_correlation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_query', sa.String(length=256), nullable=False),
    sa.Column('product_key', sa.String(length=512), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=True),
    sa.Column('click_count', sa.Integer(), nullable=True),
    sa.Column('impression_count', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_query', 'product_key', name='uq_query_product')
    )
    with op.batch_alter_table('query_correlation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_correlation_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_correlation_product_key'), ['product_key'], unique=False)

    op.create_table('query_failure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('normalized_query', sa.String(length=256), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_failure', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_failure_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_failure_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_failure_timestamp'), ['timestamp'], unique=False)

    op.create_table('query_impression',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_query', sa.String(length=256), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('query_impression', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_query_impression_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_query_impression_timestamp'), ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('surname', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('newsletter_opt_in', sa.Boolean(), nullable=True),
    sa.Column('privacy_accepted', sa.Boolean(), nullable=True),
    sa.Column('oauth_provider', sa.String(length=20), nullable=True),
    sa.Column('oauth_id', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('click_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=256), nullable=False),
    sa.Column('normalized_query', sa.String(length=256), nullable=False),
    sa.Column('product_key', sa.String(length=512), nullable=False),
    sa.Column('product_name', sa.String(length=512), nullable=True),
    sa.Column('site', sa.String(length=64), nullable=True),
    sa.Column('click_rank', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('click_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_click_log_normalized_query'), ['normalized_query'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_product_key'), ['product_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_query'), ['query'], unique=False)
        batch_op.create_index(batch_op.f('ix_click_log_timestamp'), ['timestamp'], unique=False)

    op.create_table('search_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('search_term', sa.String(length=256), nullable=False),
    sa.Column('filters', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_history')
    with op.batch_alter_table('click_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_click_log_timestamp'))
        batch_op.drop_index(batch_op.f('ix_click_log_query'))
        batch_op.drop_index(batch_op.f('ix_click_log_product_key'))
        batch_op.drop_index(batch_op.f('ix_click_log_normalized_query'))

    op.drop_table('click_log')
    op.drop_table('user')
    with op.batch_alter_table('query_impression', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_impression_timestamp'))
        batch_op.drop_index(batch_op.f('ix_query_impression_normalized_query'))

    op.drop_table('query_impression')
    with op.batch_alter_table('query_failure', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_failure_timestamp'))
        batch_op.drop_index(batch_op.f('ix_query_failure_query'))
        batch_op.drop_index(batch_op.f('ix_query_failure_normalized_query'))

    op.drop_table('query_failure')
    with op.batch_alter_table('query_correlation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_query_correlation_product_key'))
        batch_op.drop_index(batch_op.f('ix_query_correlation_normalized_query'))

    op.drop_table('query_correlation')
    with op.batch_alter_table('product_variant', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_variant_variant'))
        batch_op.drop_index(batch_op.f('ix_product_variant_product_key'))

    op.drop_table('product_variant')
    # ### end Alembic commands ###
